name: publish
on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install --force

      - name: Build
        run: npm run build --if-present

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17
          registry-url: "https://registry.npmjs.org"

      - name: Publish
        run: npm install && npm run build --if-present && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

