name: publish
on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Publish
        run: bun publish --access public --cwd packages/discordp
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
